//
//  WFIGMediaCollectionTest.m
//  WFInstagramAPI
//
//  Created by William Fleming on 2/11/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "WFIGMediaCollectionTest.h"

@implementation WFIGMediaCollectionTest {
  WFIGMediaCollection *_collection;
}

+ (NSString*) pageOneJSON {
  return @"{"
  "  \"pagination\":  {"
  "    \"next_url\": \"https://api.instagram.com/v1/users/980428/media/recent?access_token=testToken&count=2&max_id=387778587_980428\","
  "    \"next_max_id\": \"387778587_980428\""
  "  },"
  "  \"meta\":  {"
  "    \"code\": 200"
  "  },"
  "  \"data\":  ["
  "     {"
  "      \"tags\":  [],"
  "      \"type\": \"image\","
  "      \"location\": null,"
  "      \"comments\":  {"
  "        \"count\": 2,"
  "        \"data\":  ["
  "           {"
  "            \"created_time\": \"1328914247\","
  "            \"text\": \"foo\","
  "            \"from\":  {"
  "              \"username\": \"thorisalaptop\","
  "              \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "              \"id\": \"980428\","
  "              \"full_name\": \"thorisalaptop\""
  "            },"
  "            \"id\": \"123264102516045277\""
  "          },"
  "           {"
  "            \"created_time\": \"1328914376\","
  "            \"text\": \"bar\","
  "            \"from\":  {"
  "              \"username\": \"thorisalaptop\","
  "              \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "              \"id\": \"980428\","
  "              \"full_name\": \"thorisalaptop\""
  "            },"
  "            \"id\": \"123265180116628960\""
  "          }"
  "        ]"
  "      },"
  "      \"filter\": \"Rise\","
  "      \"created_time\": \"1323918917\","
  "      \"link\": \"http://instagr.am/p/ZMfB3/\","
  "      \"likes\":  {"
  "        \"count\": 0,"
  "        \"data\":  []"
  "      },"
  "      \"images\":  {"
  "        \"low_resolution\":  {"
  "          \"url\": \"http://distilleryimage7.s3.amazonaws.com/0381654626cb11e180c9123138016265_6.jpg\","
  "          \"width\": 306,"
  "          \"height\": 306"
  "        },"
  "        \"thumbnail\":  {"
  "          \"url\": \"http://distilleryimage7.s3.amazonaws.com/0381654626cb11e180c9123138016265_5.jpg\","
  "          \"width\": 150,"
  "          \"height\": 150"
  "        },"
  "        \"standard_resolution\":  {"
  "          \"url\": \"http://distilleryimage7.s3.amazonaws.com/0381654626cb11e180c9123138016265_7.jpg\","
  "          \"width\": 612,"
  "          \"height\": 612"
  "        }"
  "      },"
  "      \"caption\":  {"
  "        \"created_time\": \"1323918940\","
  "        \"text\": \"Not having a 13th floor I'm familiar with, but not having a 4th floor is new to me.\","
  "        \"from\":  {"
  "          \"username\": \"thorisalaptop\","
  "          \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "          \"id\": \"980428\","
  "          \"full_name\": \"thorisalaptop\""
  "        },"
  "        \"id\": \"534697801\""
  "      },"
  "      \"user_has_liked\": false,"
  "      \"id\": \"422703223_980428\","
  "      \"user\":  {"
  "        \"username\": \"thorisalaptop\","
  "        \"website\": \"\","
  "        \"bio\": \"\","
  "        \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "        \"full_name\": \"thorisalaptop\","
  "        \"id\": \"980428\""
  "      }"
  "    },"
  "     {"
  "      \"tags\":  [],"
  "      \"type\": \"image\","
  "      \"location\": null,"
  "      \"comments\":  {"
  "        \"count\": 0,"
  "        \"data\":  []"
  "      },"
  "      \"filter\": \"Rise\","
  "      \"created_time\": \"1322925711\","
  "      \"link\": \"http://instagr.am/p/XHQgb/\","
  "      \"likes\":  {"
  "        \"count\": 0,"
  "        \"data\":  []"
  "      },"
  "      \"images\":  {"
  "        \"low_resolution\":  {"
  "          \"url\": \"http://distilleryimage3.s3.amazonaws.com/86a0f7e61dc211e19e4a12313813ffc0_6.jpg\","
  "          \"width\": 306,"
  "          \"height\": 306"
  "        },"
  "        \"thumbnail\":  {"
  "          \"url\": \"http://distilleryimage3.s3.amazonaws.com/86a0f7e61dc211e19e4a12313813ffc0_5.jpg\","
  "          \"width\": 150,"
  "          \"height\": 150"
  "        },"
  "        \"standard_resolution\":  {"
  "          \"url\": \"http://distilleryimage3.s3.amazonaws.com/86a0f7e61dc211e19e4a12313813ffc0_7.jpg\","
  "          \"width\": 612,"
  "          \"height\": 612"
  "        }"
  "      },"
  "      \"caption\":  {"
  "        \"created_time\": \"1322925751\","
  "        \"text\": \"Backyards in Carroll Gardens are *gargantuan*.\","
  "        \"from\":  {"
  "          \"username\": \"thorisalaptop\","
  "          \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "          \"id\": \"980428\","
  "          \"full_name\": \"thorisalaptop\""
  "        },"
  "        \"id\": \"489881035\""
  "      },"
  "      \"user_has_liked\": false,"
  "      \"id\": \"387778587_980428\","
  "      \"user\":  {"
  "        \"username\": \"thorisalaptop\","
  "        \"website\": \"\","
  "        \"bio\": \"\","
  "        \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "        \"full_name\": \"thorisalaptop\","
  "        \"id\": \"980428\""
  "      }"
  "    }"
  "  ]"
  "}";
}

+ (NSString*) pageTwoJSON {
  return @"{"
  "  \"pagination\":  {"
  "    \"next_url\": \"https://api.instagram.com/v1/users/980428/media/recent?access_token=testToken&count=2&max_id=370467686_980428\","
  "    \"next_max_id\": \"370467686_980428\""
  "  },"
  "  \"meta\":  {"
  "    \"code\": 200"
  "  },"
  "  \"data\":  ["
  "     {"
  "      \"tags\":  [],"
  "      \"type\": \"image\","
  "      \"location\": null,"
  "      \"comments\":  {"
  "        \"count\": 0,"
  "        \"data\":  []"
  "      },"
  "      \"filter\": \"Hefe\","
  "      \"created_time\": \"1322606130\","
  "      \"link\": \"http://instagr.am/p/Wh1wC/\","
  "      \"likes\":  {"
  "        \"count\": 1,"
  "        \"data\":  ["
  "           {"
  "            \"username\": \"qmqm\","
  "            \"profile_picture\": \"http://images.instagram.com/profiles/profile_953328_75sq_1294273061.jpg\","
  "            \"id\": \"953328\","
  "            \"full_name\": \"Quinn\""
  "          }"
  "        ]"
  "      },"
  "      \"images\":  {"
  "        \"low_resolution\":  {"
  "          \"url\": \"http://distilleryimage2.s3.amazonaws.com/715d9b861ada11e19896123138142014_6.jpg\","
  "          \"width\": 306,"
  "          \"height\": 306"
  "        },"
  "        \"thumbnail\":  {"
  "          \"url\": \"http://distilleryimage2.s3.amazonaws.com/715d9b861ada11e19896123138142014_5.jpg\","
  "          \"width\": 150,"
  "          \"height\": 150"
  "        },"
  "        \"standard_resolution\":  {"
  "          \"url\": \"http://distilleryimage2.s3.amazonaws.com/715d9b861ada11e19896123138142014_7.jpg\","
  "          \"width\": 612,"
  "          \"height\": 612"
  "        }"
  "      },"
  "      \"caption\":  {"
  "        \"created_time\": \"1322606179\","
  "        \"text\": \"Seeing this when I get up from my desk is going to take some getting used to.\","
  "        \"from\":  {"
  "          \"username\": \"thorisalaptop\","
  "          \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "          \"id\": \"980428\","
  "          \"full_name\": \"thorisalaptop\""
  "        },"
  "        \"id\": \"476491742\""
  "      },"
  "      \"user_has_liked\": false,"
  "      \"id\": \"377969666_980428\","
  "      \"user\":  {"
  "        \"username\": \"thorisalaptop\","
  "        \"website\": \"\","
  "        \"bio\": \"\","
  "        \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "        \"full_name\": \"thorisalaptop\","
  "        \"id\": \"980428\""
  "      }"
  "    },"
  "     {"
  "      \"tags\":  [],"
  "      \"type\": \"image\","
  "      \"location\": null,"
  "      \"comments\":  {"
  "        \"count\": 2,"
  "        \"data\":  ["
  "           {"
  "            \"created_time\": \"1322438052\","
  "            \"text\": \"We really need to talk more often\","
  "            \"from\":  {"
  "              \"username\": \"designedbyscience\","
  "              \"profile_picture\": \"http://images.instagram.com/profiles/anonymousUser.jpg\","
  "              \"id\": \"4019882\","
  "              \"full_name\": \"Eric Haseltine\""
  "            },"
  "            \"id\": \"469713375\""
  "          },"
  "           {"
  "            \"created_time\": \"1322441011\","
  "            \"text\": \"Isn't that what I've been saying?\","
  "            \"from\":  {"
  "              \"username\": \"thorisalaptop\","
  "              \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "              \"id\": \"980428\","
  "              \"full_name\": \"thorisalaptop\""
  "            },"
  "            \"id\": \"469875225\""
  "          }"
  "        ]"
  "      },"
  "      \"filter\": \"Normal\","
  "      \"created_time\": \"1322362667\","
  "      \"link\": \"http://instagr.am/p/WFONm/\","
  "      \"likes\":  {"
  "        \"count\": 1,"
  "        \"data\":  ["
  "           {"
  "            \"username\": \"catharsis\","
  "            \"profile_picture\": \"http://images.instagram.com/profiles/profile_13046_75sq_1300349632.jpg\","
  "            \"id\": \"13046\","
  "            \"full_name\": \"Keith Chu\""
  "          }"
  "        ]"
  "      },"
  "      \"images\":  {"
  "        \"low_resolution\":  {"
  "          \"url\": \"http://distilleryimage2.s3.amazonaws.com/9605315818a311e1a87612313804ec91_6.jpg\","
  "          \"width\": 306,"
  "          \"height\": 306"
  "        },"
  "        \"thumbnail\":  {"
  "          \"url\": \"http://distilleryimage2.s3.amazonaws.com/9605315818a311e1a87612313804ec91_5.jpg\","
  "          \"width\": 150,"
  "          \"height\": 150"
  "        },"
  "        \"standard_resolution\":  {"
  "          \"url\": \"http://distilleryimage2.s3.amazonaws.com/9605315818a311e1a87612313804ec91_7.jpg\","
  "          \"width\": 612,"
  "          \"height\": 612"
  "        }"
  "      },"
  "      \"caption\":  {"
  "        \"created_time\": \"1322362684\","
  "        \"text\": \"I'm at a hockey game!\","
  "        \"from\":  {"
  "          \"username\": \"thorisalaptop\","
  "          \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "          \"id\": \"980428\","
  "          \"full_name\": \"thorisalaptop\""
  "        },"
  "        \"id\": \"466322229\""
  "      },"
  "      \"user_has_liked\": false,"
  "      \"id\": \"370467686_980428\","
  "      \"user\":  {"
  "        \"username\": \"thorisalaptop\","
  "        \"website\": \"\","
  "        \"bio\": \"\","
  "        \"profile_picture\": \"http://images.instagram.com/profiles/profile_980428_75sq_1291961825.jpg\","
  "        \"full_name\": \"thorisalaptop\","
  "        \"id\": \"980428\""
  "      }"
  "    }"
  "  ]"
  "}";
}

- (void) setUp {
  [super setUp];
  NSDictionary *firstPage = [WFIGDefaultSerializer
                             deserializeJSON:[[[self class] pageOneJSON] dataUsingEncoding:NSUTF8StringEncoding]
                             error:NULL];
  _collection = [[WFIGMediaCollection alloc] initWithJSON:firstPage];
}

- (void) testBasicFunctionality {
  STAssertEquals((NSUInteger)2, [_collection count], @"expected 2 photos, got %d", [_collection count]);
  STAssertTrue([_collection hasNextPage], @"should report having a next page");
  STAssertEqualObjects(@"https://api.instagram.com/v1/users/980428/media/recent?access_token=testToken&count=2&max_id=387778587_980428",
                       _collection.nextPageURL, @"wrong nextPageURL: ", _collection.nextPageURL);
}

- (void) testPaging {
  NSString *firstNextPageURL = _collection.nextPageURL;
  [StubNSURLConnection stubResponse:200 body:[[self class] pageTwoJSON] forURL:firstNextPageURL];
  BOOL success = [_collection loadAndMergeNextPageWithError:NULL];
  STAssertTrue(success, @"-loadAndMergeNextPageWithError should have succeeded");
  
  STAssertEquals((NSUInteger)4, [_collection count],
                 @"collection count should be 4 now, was %d", [_collection count]);
  NSString *pageTwoNextPageURL = @"https://api.instagram.com/v1/users/980428/media/recent?access_token=testToken&count=2&max_id=370467686_980428";
  STAssertEqualObjects(pageTwoNextPageURL, _collection.nextPageURL, @"next page URL should have updated");
  STAssertTrue(![firstNextPageURL isEqual:pageTwoNextPageURL], @"page URLs should be different");
  
}


@end
